trigger:
  branches:
    include:
      - main   # Run pipeline whenever code is pushed to main branch

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  # ------------------------
  # 1. BUILD & TEST STAGE
  # ------------------------
  - stage: Build
    displayName: "Build and Test"
    jobs:
      - job: BuildAndTest
        displayName: "Compile and Run Unit Tests"
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '6.x'   # Update to the .NET version your C# app uses
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: dotnet restore
            displayName: "Restore Dependencies"

          - script: dotnet build --configuration $(buildConfiguration)
            displayName: "Build Solution"

          - script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
            displayName: "Run Unit Tests"

  # ------------------------
  # 2. DEPLOY STAGE
  # ------------------------
  - stage: Deploy
    displayName: "Deploy to Test Environment"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployJob
        displayName: "Deploy Application to Test"
        steps:
          - task: DotNetCoreCLI@2
            displayName: "Publish Project"
            inputs:
              command: 'publish'
              publishWebProjects: true
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: true

          - task: PublishBuildArtifacts@1
            displayName: "Publish Build Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          # Deployment to Azure Web App
          - task: AzureWebApp@1
            displayName: "Deploy to Azure Web App (Test)"
            inputs:
              azureSubscription: '<your-service-connection>'  # Service connection name in DevOps
              appType: 'webApp'
              appName: '<your-app-name>'                      # Your Azure Web App name
              package: '$(Build.ArtifactStagingDirectory)/**/*.zip'